### ISSUE TITLE
gpib_board => x has no effect

### ISSUE THREAD

**Issue by kmaerzh** [lab-measurement/Lab-Measurement#67]
If I try to use 2 separate gpib buses, in my case 2 usb dongles, the gpib_board parameter does not seem to have an influence.
If I use something liike:
`my $instrument = new Lab::Instrument (
  connection_type => 'LinuxGPIB',
  gpib_board => 1,
  gpib_address=>10,
)`
GPIB commands are always output on port gpib0 instead of gpib1.

**Comment by amba** [comment]
Hi,

good point, actually this cannot because the board index is always set to zero in lib/Lab/Bus/LinuxGPIB.pm

`    $gpib_handle = ibdev( 0, $gpib_address, 0, 12, 1, 0 );`


The supported API is Lab::Moose, which has a new implementation of LinuxGPIB connection, see here:

https://metacpan.org/pod/Lab::Moose::Connection::LinuxGPIB

There it should be able to pass a non-zero board_index.

Best,
Simon

**Comment by kmaerzh** [comment]
Hi Simon,

thanks for your hint, with Lab::Moose it works.
And thanks for all the work on this package and providing it.

Kai
